spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems_thymeleaf?userUnicode=TRue&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gaoyuwen
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.gyw.pojo
  mapper-locations: classpath:/mapper/*
server:
  servlet:
    context-path: /ems
